#!/bin/bash

brew install act
brew install aircrack-ng
brew install amass
brew install ansible
brew install argocd-vault-plugin
brew install at-spi2-core
brew install atk
brew install autoconf
brew install awscli
brew install azure-cli
brew install base64
brew install bash
brew install bbftp-client
brew install bdw-gc
brew install black
brew install blueutil
brew install brotli
brew install c-ares
brew install ca-certificates
brew install cairo
brew install capstone
brew install certifi
brew install cffi
brew install cloud-sql-proxy
brew install colima
brew install coreutils
brew install cryptography
brew install crystal
brew install curl
brew install cyclonedx-cli
brew install dbus
brew install docker
brew install docker-buildx
brew install docker-completion
brew install docker-compose
brew install dtc
brew install emacs
brew install exiftool
brew install exploitdb
brew install feroxbuster
brew install ffuf
brew install figlet
brew install flureedb
brew install fontconfig
brew install freetype
brew install fribidi
brew install fx
brew install gdbm
brew install gdk-pixbuf
brew install gettext
brew install gh
brew install ghostscript
brew install giflib
brew install git
brew install git-filter-repo
brew install git-lfs
brew install glib
brew install gmp
brew install gnupg
brew install gnutls
brew install go
brew install gobject-introspection
brew install gobuster
brew install graphene
brew install graphite2
brew install grep
brew install gron
brew install grype
brew install gsettings-desktop-schemas
brew install gtk+3
brew install gtk4
brew install gum
brew install harfbuzz
brew install hashcat
brew install helm
brew install hicolor-icon-theme
brew install hping
brew install httpie
brew install hydra
brew install icu4c
brew install jansson
brew install jbig2dec
brew install john
brew install jpeg-turbo
brew install jq
brew install jupyterlab
brew install kind
brew install krb5
brew install kubernetes-cli
brew install kustomize
brew install libassuan
brew install libcbor
brew install libepoxy
brew install libevent
brew install libfido2
brew install libgcrypt
brew install libgit2
brew install libgit2@1.7
brew install libgpg-error
brew install libidn
brew install libidn2
brew install libkeccak
brew install libksba
brew install liblinear
brew install libnghttp2
brew install libpcap
brew install libpng
brew install libslirp
brew install libsodium
brew install libssh
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libunistring
brew install libusb
brew install libuv
brew install libx11
brew install libxau
brew install libxcb
brew install libxdmcp
brew install libxext
brew install libxfixes
brew install libxi
brew install libxrender
brew install libxtst
brew install libyaml
brew install lima
brew install little-cms2
brew install llvm
brew install llvm@15
brew install lolcat
brew install lua
brew install lz4
brew install lzo
brew install m4
brew install make
brew install mecab
brew install minikube
brew install minizip
brew install moreutils
brew install mpdecimal
brew install mysql-client
brew install ncurses
brew install nettle
brew install nikto
brew install nmap
brew install node
brew install noir
brew install npth
brew install nuclei
brew install nvm
brew install oniguruma
brew install openjdk
brew install openjpeg
brew install openldap
brew install openssl@1.1
brew install openssl@3
brew install openvpn
brew install p11-kit
brew install pandoc
brew install pango
brew install pcre
brew install pcre2
brew install pinentry
brew install pinentry-mac
brew install pipx
brew install pixman
brew install pkcs11-helper
brew install pkg-config
brew install pnpm
brew install postgresql@14
brew install py3cairo
brew install pycparser
brew install pyenv
brew install pygobject3
brew install python-argcomplete
brew install python-certifi
brew install python-cryptography
brew install python-pycurl
brew install python-setuptools
brew install python-tk@3.12
brew install python@3.10
brew install python@3.11
brew install python@3.12
brew install qemu
brew install rcm
brew install readline
brew install recode
brew install rename
brew install rlwrap
brew install rtmpdump
brew install ruby
brew install rust
brew install rustup
brew install rustup-init
brew install s3scanner
brew install sha3sum
brew install snappy
brew install snyk
brew install spark
brew install sqlite
brew install sqlmap
brew install syft
brew install tailscale
brew install tcl-tk
brew install terracognita
brew install terraform
brew install terraformer
brew install tfenv
brew install tfswitch
brew install the_silver_searcher
brew install tmux
brew install tree
brew install tree-sitter
brew install trivy
brew install trufflehog
brew install unbound
brew install utf8proc
brew install vde
brew install virustotal-cli
brew install vte3
brew install wget
brew install wpscan
brew install xorgproto
brew install xxhash
brew install xz
brew install yq
brew install z3
brew install zeromq
brew install zlib
brew install zstd
brew install --cask cf-terraforming
brew install --cask chromium
brew install --cask ghidra
brew install --cask graphiql
brew install --cask miniforge
brew install --cask powershell
brew install --cask raycast
brew install --cask warp

cat brew_install_commands.sh
#!/bin/bash

brew install act
brew install aircrack-ng
brew install amass
brew install ansible
brew install argocd-vault-plugin
brew install at-spi2-core
brew install atk
brew install autoconf
brew install awscli
brew install azure-cli
brew install base64
brew install bash
brew install bbftp-client
brew install bdw-gc
brew install black
brew install blueutil
brew install brotli
brew install c-ares
brew install ca-certificates
brew install cairo
brew install capstone
brew install certifi
brew install cffi
brew install cloud-sql-proxy
brew install colima
brew install coreutils
brew install cryptography
brew install crystal
brew install curl
brew install cyclonedx-cli
brew install dbus
brew install docker
brew install docker-buildx
brew install docker-completion
brew install docker-compose
brew install dtc
brew install emacs
brew install exiftool
brew install exploitdb
brew install feroxbuster
brew install ffuf
brew install figlet
brew install flureedb
brew install fontconfig
brew install freetype
brew install fribidi
brew install fx
brew install gdbm
brew install gdk-pixbuf
brew install gettext
brew install gh
brew install ghostscript
brew install giflib
brew install git
brew install git-filter-repo
brew install git-lfs
brew install glib
brew install gmp
brew install gnupg
brew install gnutls
brew install go
brew install gobject-introspection
brew install gobuster
brew install graphene
brew install graphite2
brew install grep
brew install gron
brew install grype
brew install gsettings-desktop-schemas
brew install gtk+3
brew install gtk4
brew install gum
brew install harfbuzz
brew install hashcat
brew install helm
brew install hicolor-icon-theme
brew install hping
brew install httpie
brew install hydra
brew install icu4c
brew install jansson
brew install jbig2dec
brew install john
brew install jpeg-turbo
brew install jq
brew install jupyterlab
brew install kind
brew install krb5
brew install kubernetes-cli
brew install kustomize
brew install libassuan
brew install libcbor
brew install libepoxy
brew install libevent
brew install libfido2
brew install libgcrypt
brew install libgit2
brew install libgit2@1.7
brew install libgpg-error
brew install libidn
brew install libidn2
brew install libkeccak
brew install libksba
brew install liblinear
brew install libnghttp2
brew install libpcap
brew install libpng
brew install libslirp
brew install libsodium
brew install libssh
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libunistring
brew install libusb
brew install libuv
brew install libx11
brew install libxau
brew install libxcb
brew install libxdmcp
brew install libxext
brew install libxfixes
brew install libxi
brew install libxrender
brew install libxtst
brew install libyaml
brew install lima
brew install little-cms2
brew install llvm
brew install llvm@15
brew install lolcat
brew install lua
brew install lz4
brew install lzo
brew install m4
brew install make
brew install mecab
brew install minikube
brew install minizip
brew install moreutils
brew install mpdecimal
brew install mysql-client
brew install ncurses
brew install nettle
brew install nikto
brew install nmap
brew install node
brew install noir
brew install npth
brew install nuclei
brew install nvm
brew install oniguruma
brew install openjdk
brew install openjpeg
brew install openldap
brew install openssl@1.1
brew install openssl@3
brew install openvpn
brew install p11-kit
brew install pandoc
brew install pango
brew install pcre
brew install pcre2
brew install pinentry
brew install pinentry-mac
brew install pipx
brew install pixman
brew install pkcs11-helper
brew install pkg-config
brew install pnpm
brew install postgresql@14
brew install py3cairo
brew install pycparser
brew install pyenv
brew install pygobject3
brew install python-argcomplete
brew install python-certifi
brew install python-cryptography
brew install python-pycurl
brew install python-setuptools
brew install python-tk@3.12
brew install python@3.10
brew install python@3.11
brew install python@3.12
brew install qemu
brew install rcm
brew install readline
brew install recode
brew install rename
brew install rlwrap
brew install rtmpdump
brew install ruby
brew install rust
brew install rustup
brew install rustup-init
brew install s3scanner
brew install sha3sum
brew install snappy
brew install snyk
brew install spark
brew install sqlite
brew install sqlmap
brew install syft
brew install tailscale
brew install tcl-tk
brew install terracognita
brew install terraform
brew install terraformer
brew install tfenv
brew install tfswitch
brew install the_silver_searcher
brew install tmux
brew install tree
brew install tree-sitter
brew install trivy
brew install trufflehog
brew install unbound
brew install utf8proc
brew install vde
brew install virustotal-cli
brew install vte3
brew install wget
brew install wpscan
brew install xorgproto
brew install xxhash
brew install xz
brew install yq
brew install z3
brew install zeromq
brew install zlib
brew install zstd
brew install --cask cf-terraforming
brew install --cask chromium
brew install --cask ghidra
brew install --cask graphiql
brew install --cask miniforge
brew install --cask powershell
brew install --cask raycast
brew install --cask warp
